trigger:
- main

variables:
  AGENT_TOOLSDIRECTORY: $(Agent.TempDirectory)/toolcache

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    node -v
    npm -v
  displayName: 'Show Node & npm versions'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'

- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2_art'
    cliInstallationRepo: 'jfrog-cli-v2'
    installCustomVersion: true
    cliVersion: '2.77.0'
