trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    node -v
    npm -v
  displayName: 'Show Node & npm versions'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'

- script: |
    sudo rm -rf /opt/hostedtoolcache/jf
    sudo rm -rf /opt/hostedtoolcache/_jf
  displayName: 'Clear JFrog CLI cache'

- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2_art'
    cliInstallationRepo: 'jfrog-cli-v2'
    installCustomVersion: true
    cliVersion: '2.78.0'
